# Generated by Django 5.2.1 on 2025-05-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeuModelo',
            new_name='Consulta',
        ),
    ]
