# Generated by Django 5.2.1 on 2025-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_rename_meumodelo_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
                ('idade', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
